# Generated by Django 4.0.5 on 2022-07-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_autor_livro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='editora', to='core.editora'),
            preserve_default=False,
        ),
    ]
